-- =====================================================================
-- Migration: Call KPI tracking + Email outbox (CRM Pipeline v1.0 BA doc)
-- =====================================================================

-- Verified call sessions (anti-fake: duration, dedup and anomaly flags
-- are enforced by the app and auditable here).
create table if not exists call_logs (
  id            text primary key,
  seq           bigint generated by default as identity,
  "repId"       text,
  "repName"     text,
  "targetType"  text, -- lead | contact
  "targetId"    text,
  "targetName"  text,
  phone         text,
  "startedAt"   text,
  "endedAt"     text,
  "durationSec" numeric,
  reached       boolean,
  "failReason"  text,
  note          text,
  "dateKey"     text, -- YYYY-MM-DD, for daily KPI grouping
  flagged       boolean default false, -- anomaly detector mark
  extra         jsonb default '{}'::jsonb
);
create index if not exists idx_call_logs_rep_date on call_logs ("repId", "dateKey");

-- Every notification email the system tries to send (sent | failed | skipped)
create table if not exists email_outbox (
  id            text primary key,
  seq           bigint generated by default as identity,
  "toEmail"     text,
  "toName"      text,
  subject       text,
  body          text,
  "relatedType" text,
  "relatedId"   text,
  status        text, -- pending | sent | failed | skipped
  error         text,
  "createdAt"   text,
  "sentAt"      text,
  extra         jsonb default '{}'::jsonb
);

do $$
declare t text;
begin
  foreach t in array array['call_logs','email_outbox'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "demo_full_access" on %I', t);
    execute format(
      'create policy "demo_full_access" on %I for all to anon, authenticated using (true) with check (true)', t
    );
  end loop;
end $$;

-- Parameterized per-rep settings stored as DATA on the staff profile:
-- notification email + daily call KPI target. Editable from the app UI.
update staff_users
set extra = coalesce(extra, '{}'::jsonb) || jsonb_build_object('kpiDailyCalls', 100)
where role = 'sales' and not (coalesce(extra, '{}'::jsonb) ? 'kpiDailyCalls');

update staff_users
set extra = coalesce(extra, '{}'::jsonb) || jsonb_build_object('notifyEmail', 'trieudv.mcna.247@gmail.com')
where id = 'usr-sales';
