-- =====================================================================
-- MCNA CRM VN - Supabase Schema
-- Mirrors the in-app data model (src/crm-database.js).
-- Column names are quoted camelCase so rows map 1:1 to the JS objects.
-- Each table has an `extra jsonb` catch-all for fields the app adds at
-- runtime, and a `seq` identity used only for stable ordering.
-- =====================================================================

create table if not exists staff_users (
  id            text primary key,
  seq           bigint generated by default as identity,
  email         text unique,
  pw            text,
  name          text,
  role          text, -- superadmin | manager (marketers) | sales | support
  dept          text,
  phone         text,
  initials      text,
  color         text,
  status        text default 'active',
  "joinedAt"    text,
  "lastLogin"   text,
  target        numeric,
  "dealsWon"    numeric,
  revenue       numeric,
  extra         jsonb default '{}'::jsonb
);

create table if not exists companies (
  id              text primary key,
  seq             bigint generated by default as identity,
  name            text,
  industry        text,
  size            text,
  website         text,
  phone           text,
  address         text,
  "contactsCount" numeric,
  "dealsCount"    numeric,
  revenue         numeric,
  "ownerId"       text,
  notes           text,
  extra           jsonb default '{}'::jsonb
);

-- B2C customers live here (companyId is null for B2C)
create table if not exists contacts (
  id             text primary key,
  seq            bigint generated by default as identity,
  "firstName"    text,
  "lastName"     text,
  "fullName"     text,
  title          text,
  "companyId"    text,
  "companyName"  text,
  phone          text,
  email          text,
  source         text,
  "ownerId"      text,
  tags           jsonb,
  "dealsCount"   numeric,
  "lastActivity" text,
  "createdAt"    text,
  notes          text,
  extra          jsonb default '{}'::jsonb
);

create table if not exists leads (
  id          text primary key,
  seq         bigint generated by default as identity,
  "leadType"  text, -- b2c | b2b
  name        text,
  company     text,
  phone       text,
  email       text,
  source      text,
  status      text, -- new | contacting | qualified | proposal | lost | pending_assignment
  value       numeric,
  "ownerId"   text,
  "createdAt" text,
  deadline    text,
  priority    text, -- hot | warm | cold
  notes       text,
  tags        jsonb,
  extra       jsonb default '{}'::jsonb
);

create table if not exists deals (
  id              text primary key,
  seq             bigint generated by default as identity,
  name            text,
  "contactId"     text,
  "contactName"   text,
  "companyId"     text,
  "companyName"   text,
  value           numeric,
  stage           text, -- prospecting | qualified | proposal | negotiation | closed_won | closed_lost | nurtured
  probability     numeric,
  "ownerId"       text,
  "expectedClose" text,
  "createdAt"     text,
  "lastActivity"  text,
  notes           text,
  tags            jsonb,
  extra           jsonb default '{}'::jsonb
);

create table if not exists tasks (
  id          text primary key,
  seq         bigint generated by default as identity,
  title       text,
  type        text,
  description text,
  "relatedTo" text,
  "relatedId" text,
  "ownerId"   text,
  "dueDate"   text,
  priority    text,
  status      text,
  completed   boolean,
  subtasks    jsonb,
  tags        jsonb,
  extra       jsonb default '{}'::jsonb
);

create table if not exists activities (
  id          text primary key,
  seq         bigint generated by default as identity,
  type        text,
  title       text,
  "contactId" text,
  "dealId"    text,
  "ownerId"   text,
  datetime    text,
  date        text,
  duration    text,
  outcome     text,
  notes       text,
  direction   text,
  "user"      text,
  extra       jsonb default '{}'::jsonb
);

create table if not exists products (
  id          text primary key,
  seq         bigint generated by default as identity,
  name        text,
  code        text,
  category    text,
  price       numeric,
  unit        text,
  stock       numeric,
  description text,
  emoji       text,
  status      text,
  extra       jsonb default '{}'::jsonb
);

create table if not exists quotes (
  id            text primary key,
  seq           bigint generated by default as identity,
  number        text,
  "contactId"   text,
  "contactName" text,
  "dealId"      text,
  items         jsonb,
  subtotal      numeric,
  vat           numeric,
  total         numeric,
  status        text,
  "createdAt"   text,
  "validUntil"  text,
  "ownerId"     text,
  terms         text,
  notes         text,
  extra         jsonb default '{}'::jsonb
);

create table if not exists invoices (
  id            text primary key,
  seq           bigint generated by default as identity,
  number        text,
  "quoteId"     text,
  "contactId"   text,
  "contactName" text,
  "dealId"      text,
  "companyName" text,
  items         jsonb,
  amount        numeric,
  total         numeric,
  status        text, -- paid | partial | overdue | pending
  "dueDate"     text,
  "paidAt"      text,
  "createdAt"   text,
  notes         text,
  extra         jsonb default '{}'::jsonb
);

create table if not exists tickets (
  id            text primary key,
  seq           bigint generated by default as identity,
  number        text,
  subject       text,
  "contactId"   text,
  "contactName" text,
  channel       text,
  priority      text,
  status        text,
  "agentId"     text,
  "createdAt"   text,
  "lastReply"   text,
  "slaHours"    numeric,
  tags          jsonb,
  messages      jsonb,
  extra         jsonb default '{}'::jsonb
);

create table if not exists audit_log (
  id        text primary key,
  seq       bigint generated by default as identity,
  timestamp text,
  "user"    text,
  action    text,
  resource  text,
  ip        text,
  status    text,
  extra     jsonb default '{}'::jsonb
);

create table if not exists notifications (
  id        text primary key,
  seq       bigint generated by default as identity,
  type      text,
  title     text,
  body      text,
  content   text,
  time      text,
  unread    boolean,
  "userId"  text,
  "user"    text,
  extra     jsonb default '{}'::jsonb
);

create table if not exists revenue_months (
  id         text primary key,
  seq        bigint generated by default as identity,
  month      text,
  revenue    numeric,
  "wonDeals" numeric
);

-- ---------------------------------------------------------------------
-- Row Level Security: demo-grade open access for the anon key.
-- The app does its own role-based gating client-side; tighten these
-- policies before using with real customer data.
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'staff_users','companies','contacts','leads','deals','tasks',
    'activities','products','quotes','invoices','tickets',
    'audit_log','notifications','revenue_months'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "demo_full_access" on %I', t);
    execute format(
      'create policy "demo_full_access" on %I for all to anon, authenticated using (true) with check (true)', t
    );
  end loop;
end $$;
